package com.ecommerce.project.service;

import com.ecommerce.project.api.response.model.ProductResponse;
import com.ecommerce.project.dtos.ProductDTO;
import com.ecommerce.project.exceptions.custom.APIException;
import com.ecommerce.project.exceptions.custom.ResourceAlreadyPresentException;
import com.ecommerce.project.exceptions.custom.ResourceNotFoundException;
import com.ecommerce.project.model.Category;
import com.ecommerce.project.model.Product;
import com.ecommerce.project.repository.CategoryRepository;
import com.ecommerce.project.repository.ProductRepository;
import org.modelmapper.ModelMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.util.List;
import java.util.concurrent.atomic.AtomicBoolean;

@Service
public class ProductServiceImpl implements ProductService {

    @Autowired
    private CategoryRepository categoryRepository;

    @Autowired
    private ProductRepository productRepository;

    @Autowired
    private FileService fileService;

    @Autowired
    private ModelMapper modelMapper;

    @Override
    public ProductDTO addProduct(Long categoryId, ProductDTO productDTO) {
        Product newProduct = modelMapper.map(productDTO, Product.class);
        Category category = categoryRepository.findById(categoryId).orElseThrow(() -> new ResourceNotFoundException(categoryId, "categoryId", "Category"));
        AtomicBoolean isProductNotPresent = new AtomicBoolean(true);
        List<Product> productList = category.getProducts();

        for (Product product : productList) {
            if (product.getProductName().equalsIgnoreCase(newProduct.getProductName())) {
                isProductNotPresent.set(false);
                break;
            }
        }

        if (isProductNotPresent.get()) {
            newProduct.setCategory(category);
            newProduct.setImage("autoGeneratedImg.png");
            double specialPrice = newProduct.getPrice() - (newProduct.getPrice() * (newProduct.getDiscount() / 100));
            newProduct.setSpecialPrice(specialPrice);
            return modelMapper.map(productRepository.save(newProduct), ProductDTO.class);
        } else {
            throw new ResourceAlreadyPresentException("Product", "ProductName", newProduct.getProductName());
        }

    }

    @Override
    public ProductResponse getAllProducts(Integer pageNumber, Integer pageSize, String sortBy, String sortOrder) {
        Sort sortDetailsObj = sortOrder.equalsIgnoreCase("asc") ? Sort.by(sortBy).ascending() : Sort.by(sortBy).descending();
        Pageable pageable = PageRequest.of(pageNumber, pageSize, sortDetailsObj);

        Page<Product> productPage = productRepository.findAll(pageable);
        List<Product> productList = productPage.getContent();
        List<ProductDTO> productDTOList = productList.stream().map(product -> modelMapper.map(product, ProductDTO.class)).toList();
        checkIsProductListEmpty(1, null, productDTOList);

        ProductResponse productResponse = new ProductResponse();
        productResponse.setContent(productDTOList);
        productResponse.setPageNumber(pageable.getPageNumber());
        productResponse.setPageSize(pageable.getPageSize());
        productResponse.setTotalPages(productPage.getTotalPages());
        productResponse.setTotalElements(productPage.getTotalElements());
        productResponse.setIsLastPage(productPage.isLast());
        return productResponse;
    }

    @Override
    public ProductResponse getCategoryWiseAllProducts(Long categoryId, Integer pageNumber, Integer pageSize, String sortBy, String sortOrder) {
        Sort sortDetailsObj = sortOrder.equalsIgnoreCase("asc") ? Sort.by(sortBy).ascending() : Sort.by(sortBy).descending();
        Pageable pageable = PageRequest.of(pageNumber, pageSize, sortDetailsObj);

        Category category = categoryRepository.findById(categoryId).orElseThrow(() -> new ResourceNotFoundException(categoryId, "categoryId", "Category"));
        Page<Product> productListPage = productRepository.findByCategoryOrderByPriceAsc(pageable, category);

        List<Product> products = productListPage.toList();
        List<ProductDTO> productDTOList = products.stream().map(product -> modelMapper.map(product, ProductDTO.class)).toList();
        checkIsProductListEmpty(2, category.getCategoryName() , productDTOList);

        // DTO logic
        ProductResponse productResponse = new ProductResponse();
        productResponse.setContent(productDTOList);
        productResponse.setPageNumber(pageable.getPageNumber());
        productResponse.setPageSize(pageable.getPageSize());
        productResponse.setTotalPages(productListPage.getTotalPages());
        productResponse.setTotalElements(productListPage.getTotalElements());
        productResponse.setIsLastPage(productListPage.isLast());
        return productResponse;
    }

    @Override
    public ProductResponse getProductsByKeyword(String keyword, Integer pageNumber, Integer pageSize, String sortBy, String sortOrder) {

        Sort sortDetailsObj = sortOrder.equalsIgnoreCase("asc") ? Sort.by(sortBy).ascending() : Sort.by(sortBy).descending();
        Pageable pageable = PageRequest.of(pageNumber, pageSize, sortDetailsObj);

        Page<Product> productListPage = productRepository.findByProductNameLikeIgnoreCaseOrderByPriceAsc("%" + keyword + "%", pageable);
        List<Product> productList = productListPage.getContent();
        List<ProductDTO> productDTOList = productList.stream().map(product -> modelMapper.map(product, ProductDTO.class)).toList();
        checkIsProductListEmpty(3, keyword, productDTOList);

        // DTO logic
        ProductResponse productResponse = new ProductResponse();
        productResponse.setContent(productDTOList);
        productResponse.setPageNumber(pageable.getPageNumber());
        productResponse.setPageSize(pageable.getPageSize());
        productResponse.setTotalPages(productListPage.getTotalPages());
        productResponse.setTotalElements(productListPage.getTotalElements());
        productResponse.setIsLastPage(productListPage.isLast());
        return productResponse;
    }

    @Override
    public ProductDTO updateProduct(Long productId, ProductDTO productDTO) {
        Product product = productRepository.findById(productId).orElseThrow(() -> new ResourceNotFoundException(productId, "productId", "Product"));
        product.setProductName(productDTO.getProductName());
        product.setDescription(productDTO.getDescription());
        product.setQuantity(productDTO.getQuantity());
        product.setDiscount(productDTO.getDiscount());
        product.setPrice(productDTO.getPrice());
        double specialPrice = product.getPrice() - (product.getPrice() * (product.getDiscount() / 100));
        product.setSpecialPrice(specialPrice);
        productRepository.save(product);
        return modelMapper.map(product, ProductDTO.class);
    }

    @Override
    public ProductDTO updateProductImage(Long productId, MultipartFile image) throws IOException {
        Product product = productRepository.findById(productId).orElseThrow(() -> new ResourceNotFoundException(productId, "productId", "Product"));
        String fileName = fileService.uploadImageFile(image);
        product.setImage(fileName);
        return modelMapper.map(productRepository.save(product), ProductDTO.class);

    }

    @Override
    public ProductDTO deleteProduct(Long productId) {
        Product product = productRepository.findById(productId).orElseThrow(() -> new ResourceNotFoundException(productId, "productId", "Product"));
        productRepository.delete(product);
        return modelMapper.map(product, ProductDTO.class);
    }

    void checkIsProductListEmpty(int executionFlag, String value, List<ProductDTO> productDTOList) {
        switch (executionFlag) {
            case 1 -> {
                if (productDTOList.isEmpty()) {
                    throw new APIException("No products present till now");
                }
            }
            case 2 -> {
                if (productDTOList.isEmpty()) {
                    throw new APIException("No products available in " + value + " category");
                }
            }
            case 3 -> {
                if (productDTOList.isEmpty()) {
                    throw new APIException("No products found with search keyword: " + value);
                }
            }
            default -> throw new IllegalStateException("Unexpected value: " + executionFlag);
        }
    }

}
